/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	egressiptrafficv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressiptraffic/v1"
)

// EgressIPTrafficSpecApplyConfiguration represents a declarative configuration of the EgressIPTrafficSpec type for use
// with apply.
type EgressIPTrafficSpecApplyConfiguration struct {
	TrafficMatchers []egressiptrafficv1.TrafficMatcher `json:"trafficMatchers,omitempty"`
}

// EgressIPTrafficSpec constructs a declarative configuration of the EgressIPTrafficSpec type for use with
// apply.
func EgressIPTrafficSpec() *EgressIPTrafficSpecApplyConfiguration {
	return &EgressIPTrafficSpecApplyConfiguration{}
}

// WithTrafficMatchers adds the given value to the TrafficMatchers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TrafficMatchers field.
func (b *EgressIPTrafficSpecApplyConfiguration) WithTrafficMatchers(values ...egressiptrafficv1.TrafficMatcher) *EgressIPTrafficSpecApplyConfiguration {
	for i := range values {
		b.TrafficMatchers = append(b.TrafficMatchers, values[i])
	}
	return b
}
